/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.ulp.lab_tp4;

/**
 *
 * @author NoxiePC
 */
public class Forminscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Forminscripcion
     */
    public Forminscripcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBoxMateria = new javax.swing.JComboBox<>();
        CBoxAlumno = new javax.swing.JComboBox<>();
        btnInscribir = new javax.swing.JButton();
        btnSalirInscrip = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inscripcion");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de Inscripción");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Elija una Materia:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Elija un Alumno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        CBoxMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CBoxMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, -1));

        CBoxAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CBoxAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, -1));

        btnInscribir.setText("Inscribir");
        getContentPane().add(btnInscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        btnSalirInscrip.setText("Salir");
        getContentPane().add(btnSalirInscrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBoxAlumno;
    private javax.swing.JComboBox<String> CBoxMateria;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnSalirInscrip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
