/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.ulp.lab_tp4;

/**
 *
 * @author NoxiePC
 */
public class Formmaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form Formmaterias
     */
    public Formmaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodMateria = new javax.swing.JTextField();
        txtNombreMateria = new javax.swing.JTextField();
        txtAñoMateria = new javax.swing.JTextField();
        btnGuardarMaterias = new javax.swing.JButton();
        btnNuevoMaterias = new javax.swing.JButton();
        btnSalirMaterias = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Materias");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de Materias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 200, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Codigo de Materias:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre de la Materia:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Año al que pertenece:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        getContentPane().add(txtCodMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 80, -1));
        getContentPane().add(txtNombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 210, -1));
        getContentPane().add(txtAñoMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 210, -1));

        btnGuardarMaterias.setText("Guardar");
        getContentPane().add(btnGuardarMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        btnNuevoMaterias.setText("Nuevo");
        getContentPane().add(btnNuevoMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        btnSalirMaterias.setText("Salir");
        getContentPane().add(btnSalirMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarMaterias;
    private javax.swing.JButton btnNuevoMaterias;
    private javax.swing.JButton btnSalirMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAñoMateria;
    private javax.swing.JTextField txtCodMateria;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
