/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.ulp.lab_tp4;

import javax.swing.JOptionPane;

/**
 *
 * @author NoxiePC
 */
public class Formmaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form Formmaterias
     */
    public Formmaterias() {
        initComponents();
    }
    private void limpiarformulario(){
        txtCodMateria.setText("");
        txtNombreMateria.setText("");
        txtAñoMateria.setText("");
        
        txtCodMateria.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodMateria = new javax.swing.JTextField();
        txtNombreMateria = new javax.swing.JTextField();
        txtAñoMateria = new javax.swing.JTextField();
        btnGuardarMaterias = new javax.swing.JButton();
        btnNuevoMaterias = new javax.swing.JButton();
        btnSalirMaterias = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta de Materias");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de Materias");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Codigo de Materias:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre de la Materia:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Año al que pertenece:");

        btnGuardarMaterias.setText("Guardar");
        btnGuardarMaterias.addActionListener(this::btnGuardarMateriasActionPerformed);

        btnNuevoMaterias.setText("Nuevo");
        btnNuevoMaterias.addActionListener(this::btnNuevoMateriasActionPerformed);

        btnSalirMaterias.setText("Salir");
        btnSalirMaterias.addActionListener(this::btnSalirMateriasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(txtCodMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(txtAñoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnGuardarMaterias)
                .addGap(18, 18, 18)
                .addComponent(btnNuevoMaterias)
                .addGap(18, 18, 18)
                .addComponent(btnSalirMaterias))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtCodMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtAñoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarMaterias)
                    .addComponent(btnNuevoMaterias)
                    .addComponent(btnSalirMaterias)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMateriasActionPerformed
        int codigo = Integer.parseInt(txtCodMateria.getText());
        String nombre = txtNombreMateria.getText();
        int anio = Integer.parseInt(txtAñoMateria.getText());
        
        Materia a = new Materia(codigo, nombre, anio);
        VentanaPrincipal.listaMaterias.add(a);
        JOptionPane.showMessageDialog(this, "Materia agregada correctamente");
    }//GEN-LAST:event_btnGuardarMateriasActionPerformed

    private void btnSalirMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMateriasActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnSalirMateriasActionPerformed

    private void btnNuevoMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoMateriasActionPerformed
       limpiarformulario();
    }//GEN-LAST:event_btnNuevoMateriasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarMaterias;
    private javax.swing.JButton btnNuevoMaterias;
    private javax.swing.JButton btnSalirMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAñoMateria;
    private javax.swing.JTextField txtCodMateria;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
