/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

/**
 *
 * @author Juan
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAlumno = new javax.swing.JMenu();
        MenuAgregarAlumno = new javax.swing.JMenuItem();
        MenuVistaAlumno = new javax.swing.JMenuItem();
        MenuMateria = new javax.swing.JMenu();
        MenuAgregarMateria = new javax.swing.JMenuItem();
        MenuVistaMateria = new javax.swing.JMenuItem();
        MenuRegistro = new javax.swing.JMenu();
        MenuInscribir = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        MenuAlumno.setText("Alumno");

        MenuAgregarAlumno.setText("Agregar Alumno");
        MenuAlumno.add(MenuAgregarAlumno);

        MenuVistaAlumno.setText("Vista Alumnos");
        MenuAlumno.add(MenuVistaAlumno);

        jMenuBar1.add(MenuAlumno);

        MenuMateria.setText("Materia");

        MenuAgregarMateria.setText("Agregar Materia");
        MenuMateria.add(MenuAgregarMateria);

        MenuVistaMateria.setText("Vista Materia");
        MenuMateria.add(MenuVistaMateria);

        jMenuBar1.add(MenuMateria);

        MenuRegistro.setText("Registro");

        MenuInscribir.setText("Inscribir");
        MenuRegistro.add(MenuInscribir);

        jMenuBar1.add(MenuRegistro);

        MenuSalir.setText("Salir");

        jMenuItem6.setText("Salir");
        MenuSalir.add(jMenuItem6);

        jMenuBar1.add(MenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAgregarAlumno;
    private javax.swing.JMenuItem MenuAgregarMateria;
    private javax.swing.JMenu MenuAlumno;
    private javax.swing.JMenuItem MenuInscribir;
    private javax.swing.JMenu MenuMateria;
    private javax.swing.JMenu MenuRegistro;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenuItem MenuVistaAlumno;
    private javax.swing.JMenuItem MenuVistaMateria;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
