/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ulp.lab_tp4;

import java.util.HashSet;

/**
 *
 * @author Juan
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    public static HashSet<Alumno> listaAlumnos = new HashSet<>();
    public static HashSet<Materia> listaMaterias = new HashSet<>();
    
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAlumno = new javax.swing.JMenu();
        MenuAgregarAlumno = new javax.swing.JMenuItem();
        MenuVistaAlumno = new javax.swing.JMenuItem();
        MenuMateria = new javax.swing.JMenu();
        MenuAgregarMateria = new javax.swing.JMenuItem();
        MenuVistaMateria = new javax.swing.JMenuItem();
        MenuRegistro = new javax.swing.JMenu();
        MenuInscribir = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        MenuAlumno.setText("Alumno");

        MenuAgregarAlumno.setText("Agregar Alumno");
        MenuAgregarAlumno.addActionListener(this::MenuAgregarAlumnoActionPerformed);
        MenuAlumno.add(MenuAgregarAlumno);

        MenuVistaAlumno.setText("Vista Alumnos");
        MenuAlumno.add(MenuVistaAlumno);

        jMenuBar1.add(MenuAlumno);

        MenuMateria.setText("Materia");

        MenuAgregarMateria.setText("Agregar Materia");
        MenuAgregarMateria.addActionListener(this::MenuAgregarMateriaActionPerformed);
        MenuMateria.add(MenuAgregarMateria);

        MenuVistaMateria.setText("Vista Materia");
        MenuMateria.add(MenuVistaMateria);

        jMenuBar1.add(MenuMateria);

        MenuRegistro.setText("Registro");

        MenuInscribir.setText("Inscribir");
        MenuInscribir.addActionListener(this::MenuInscribirActionPerformed);
        MenuRegistro.add(MenuInscribir);

        jMenuBar1.add(MenuRegistro);

        MenuSalir.setText("Salir");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        MenuSalir.add(btnSalir);

        jMenuBar1.add(MenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgregarAlumnoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Formalumno ventanaAlumno = new Formalumno();
        ventanaAlumno.setVisible(true);
        escritorio.add(ventanaAlumno);
    }//GEN-LAST:event_MenuAgregarAlumnoActionPerformed

    private void MenuAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgregarMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Formmaterias ventanaMaterias = new Formmaterias();
        ventanaMaterias.setVisible(true);
        escritorio.add(ventanaMaterias);
    }//GEN-LAST:event_MenuAgregarMateriaActionPerformed

    private void MenuInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInscribirActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Forminscripcion ventanaInscripcion = new Forminscripcion();
        ventanaInscripcion.setVisible(true);
        escritorio.add(ventanaInscripcion);
    }//GEN-LAST:event_MenuInscribirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAgregarAlumno;
    private javax.swing.JMenuItem MenuAgregarMateria;
    private javax.swing.JMenu MenuAlumno;
    private javax.swing.JMenuItem MenuInscribir;
    private javax.swing.JMenu MenuMateria;
    private javax.swing.JMenu MenuRegistro;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenuItem MenuVistaAlumno;
    private javax.swing.JMenuItem MenuVistaMateria;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
